config/routes.rb
# The generic format is like so:
# HTTPVERB ‘URL’ => 
# “CONTROLLER#VIEW”


Rails.application.routes.draw do 
	get '/' => "home#index"
	get '/index' => "home#index"
	get '/join' => "home#join"
 	get '/contact' => "home#contact"
 	get '/contact/:id' => "home#contact", as: :contactus
 	get '/success' => "user#contact", as: :success
 	get '/error' => "user#contact", as: :error
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to: user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to: user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many: posts
	has_many: transactions
end

app/models/user_posts.rb
class UserPosts < ActiveRecord::Base
	belongs_to: user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@title = "Home"
	end

	def contact
		@title = "Contact"
	end

	def join
		@title = "Join"
	end

	def logo
	end

	def header
	end

	def footer
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	
def new
	@user = user.new
end

#create a html.erb file in views/user or a subfile to match the controller name

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/Contact.erb
Email us!

app/views/home/Home.erb
Welcome home

app/views/home/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRHW1</title>
 <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1>Contact us</h1>
<%= yield %>

</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRHW1</title>
 <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1>Hello World</h1>
<%= render "partials/header" %>
<%=yield %>
<%= render "partials/footer" %><%= yield %>

</body>
</html>

app/views/home/join.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRHW1</title>
 <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1>Join Us</h1>
<%= yield %>

</body>
</html>

app/views/join/Join.erb
Welcome home

app/views/layouts/alternate.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRHW1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render "form_fields", information: "sign up" %>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRHW2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "partials/header" %>
<%=yield %>
<%= render "partials/footer" %>

</body>
</html>

app/views/partials/_footer.html.erb
<footer>
   <nav class="round">
     <ul>
       <li><%= link_to "Twitter", index_path %></li>
       <li><%= link_to "Facebook", contact_path %></li>
     </ul>
   </nav>
</footer>

app/views/partials/_form_fields.html.erb
<%=information %>

app/views/partials/_header.html.erb
<header>
   <%= link_to image_tag("logo.png", :alt => "RTFTLogo", :class => "round"), index_path %>
   <nav class="round">
     <ul>
       <li><%= link_to "Home", index_path %></li>
       <li><%= link_to "Contact", contact_path %></li>
       <li><%= link_to "Join", join_path %></li>
     </ul>
   </nav>
</header>

app/views/user/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRHW1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>